theme = "gruvbox_transparent"

[editor]
auto-completion = true
clipboard-provider = "wayland"
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

